# Generated by Django 5.1.7 on 2025-06-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_movie_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='running_time',
            field=models.PositiveIntegerField(blank=True, help_text='Running time in minutes', null=True),
        ),
    ]
