# Generated by Django 5.1.7 on 2025-06-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_movie_poster_image_url_alter_movie_running_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster_image',
        ),
    ]
